telethon:
    TELEGRAM_BOT_TOKEN_hungdv_bot: 5858727806:AAEQP6GHKRm9E8tkihVp_Rg1nmStK3XOx50
    TELEGRAM_CHAT_ID_Bot-Order-HungAI: -834818909
    #-967275815
    
binance: #HungDV
    YOUR_API_KEY: LQNUXsESmgo1rABAAs648ID571DGt4V28DtcC5dCh0mXs2mxWXR2SzMT31CCOwvM
    YOUR_API_SECRET: j61OnYbDCoif8ULWRLU7lpwaqTJQbITtGhD5BNKpaewWNRyhKNey6tjLQKCYfADs
    